/** @type {import('tailwindcss').Config} */
const tailwind = require('tailwindcss/colors');
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,vue}'],
    safelist: [
        'rounded-lg',
        'mb-1',
        'text-gray-500',
        'text-red-500',
        'text-orange-500',
        'text-amber-500',
        'text-yellow-500',
        'text-lime-500',
        'text-green-500',
        'text-emerald-500',
        'text-teal-500',
        'text-cyan-500',
        'text-sky-500',
        'text-blue-500',
        'text-indigo-500',
        'text-violet-500',
        'text-purple-500',
        'text-fuchsia-500',
        'text-pink-500',
        'text-rose-500',
        'bg-gray-500',
        'bg-red-500',
        'bg-orange-500',
        'bg-amber-500',
        'bg-yellow-500',
        'bg-lime-500',
        'bg-green-500',
        'bg-emerald-500',
        'bg-teal-500',
        'bg-cyan-500',
        'bg-sky-500',
        'bg-blue-500',
        'bg-indigo-500',
        'bg-violet-500',
        'bg-purple-500',
        'bg-fuchsia-500',
        'bg-pink-500',
        'bg-rose-500',
        'bg-gray-100',
        'bg-red-100',
        'bg-orange-100',
        'bg-amber-100',
        'bg-yellow-100',
        'bg-lime-100',
        'bg-green-100',
        'bg-emerald-100',
        'bg-teal-100',
        'bg-cyan-100',
        'bg-sky-100',
        'bg-blue-100',
        'bg-indigo-100',
        'bg-violet-100',
        'bg-purple-100',
        'bg-fuchsia-100',
        'bg-pink-100',
        'bg-rose-100',
    ],
    darkMode: 'class',
    corePlugins: {
        preflight: false,
    },
    theme: {
        spacing: {
            0: '0px',
            px: '1px',
            0.5: '0.2rem',
            1: '0.4rem',
            1.5: '0.6rem',
            2: '0.8rem',
            2.5: '1rem',
            3: '1.2rem',
            3.5: '1.4rem',
            4: '1.6rem',
            4.5: '1.8rem',
            5: '2.0rem',
            6: '2.4rem',
            7: '2.8rem',
            8: '3.2rem',
            9: '3.6rem',
            10: '4.0rem',
            11: '4.4rem',
            12: '4.8rem',
            13: '5.2rem',
            14: '5.6rem',
            15: '6.0rem',
            16: '6.4rem',
            17: '6.8rem',
            18: '7.2rem',
            19: '7.6rem',
            20: '8.0rem',
            24: '9.6rem',
            28: '11.2rem',
            32: '12.8rem',
            36: '14.4rem',
            40: '16.0rem',
            44: '17.6rem',
            48: '19.2rem',
            52: '20.8rem',
            56: '22.4rem',
            60: '24rem',
            64: '25.6rem',
            72: '28.8rem',
            80: '32rem',
            96: '38.4rem',
        },
        lineHeight: {
            3: '1.2rem',
            4: '1.6rem',
            5: '2rem',
            6: '2.4rem',
            7: '2.8rem',
            8: '3.2rem',
            9: '3.6rem',
            10: '4rem',
        },
        borderRadius: {
            none: 0,
            sm: '0.2rem',
            md: '0.4rem',
            DEFAULT: '0.4rem',
            lg: '0.8rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['1.1rem', '1.6rem'],
            sm: ['1.3rem', '1.8rem'],
            base: ['1.4rem', '2rem'],
            lg: ['1.8rem', '2.6rem'],
            xl: ['2rem', '2.6rem'],
            '2xl': ['2.8rem', '3.4rem'],
            '3xl': ['3.8rem', '4.6rem'],
        },
        colors: {
            amber: tailwind.amber,
            black: tailwind.black,
            blue: tailwind.blue,
            cyan: tailwind.cyan,
            emerald: tailwind.emerald,
            fuchsia: tailwind.fuchsia,
            green: tailwind.green,
            gray: tailwind.gray,
            indigo: tailwind.indigo,
            lime: tailwind.lime,
            orange: tailwind.orange,
            pink: tailwind.pink,
            purple: tailwind.purple,
            red: tailwind.red,
            rose: tailwind.rose,
            sky: tailwind.sky,
            teal: tailwind.teal,
            transparent: tailwind.transparent,
            violet: tailwind.violet,
            white: tailwind.white,
            yellow: tailwind.yellow,
            error: tailwind.red,
            warning: tailwind.yellow,
            success: tailwind.green,
        },
        extend: {
            maxWidth: {
                0: '0px',
                none: 'none',
                xs: '20rem',
                sm: '24rem',
                md: '28rem',
                lg: '32rem',
                xl: '36rem',
                '2xl': '40rem',
            },
            fontFamily: {
                sans: [
                    'Lato',
                    'ui-sans-serif',
                    'system-ui',
                    '-apple-system',
                    'BlinkMacSystemFont',
                    '"Segoe UI"',
                    'Roboto',
                    '"Helvetica Neue"',
                    'Arial',
                    '"Noto Sans"',
                    'sans-serif',
                    '"Apple Color Emoji"',
                    '"Segoe UI Emoji"',
                    '"Segoe UI Symbol"',
                    '"Noto Color Emoji"',
                ],
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
